### ISSUE TITLE
Add help key

### ISSUE THREAD

**Issue by styu99** [styu99/haptic-device#18]
Pressing "?" will have a text window pop up with instructions/controls

**Comment by megan-le** [comment]
Press ctrl to open a very basic, not-so-aesthetically-pleasing panel that lists hotkey functions 62ddc20b0223a4075fd83b043662ca0498e77dc3

**Comment by megan-le** [comment]
Reformatted in eacfed003d87042c74a4ed6d025a72f25fca6c81
